// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sequorProduction.DataContext;

#nullable disable

namespace Sequor_production.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20240106000157_MigrationOne")]
    partial class MigrationOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity<MaterialModel>(b =>
            {
                b.Property<string>("materialCode")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("materialDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("materialCode");

                b.ToTable("Material");
            });

            modelBuilder.Entity<OrderModel>(b =>
            {
                b.Property<string>("order")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("productCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<float>("quantity")
                    .HasColumnType("real");

                b.HasKey("order");

                b.HasIndex("productCode");

                b.ToTable("Order");
            });

          modelBuilder.Entity<ProductionModel>(b =>
{
    b.Property<int>("id")
        .ValueGeneratedOnAdd()
        .HasColumnType("int");

    b.Property<float>("cycleTime")
        .ValueGeneratedOnAdd()
        .HasColumnType("real")
        .HasDefaultValue(18.2f);

    b.Property<DateTime>("date")
        .HasColumnType("datetime2");

    b.Property<string>("email")
        .IsRequired()
        .HasColumnType("nvarchar(max)");

    b.Property<string>("materialCode")
        .IsRequired()
        .HasColumnType("nvarchar(max)");

    b.Property<string>("order")
        .IsRequired()
        .HasColumnType("nvarchar(max)");

    b.Property<float>("quantity")
        .ValueGeneratedOnAdd()
        .HasColumnType("real")
        .HasDefaultValue(18.2f);

    b.HasKey("id");

    b.ToTable("Production");
});


            modelBuilder.Entity<ProductMaterial>(b =>
            {
                b.Property<string>("productCode")
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("materialCode")
                    .HasColumnType("nvarchar(450)");

                b.HasKey("productCode", "materialCode");

                b.ToTable("ProductMaterial");
            });

            modelBuilder.Entity<ProductModel>(b =>
            {
                b.Property<string>("productCode")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("nvarchar(450)");

                b.Property<float>("cycleTime")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("real")
                    .HasDefaultValue(18.2f);

                b.Property<string>("image")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("productDescription")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("productCode");

                b.ToTable("Product");
            });

            modelBuilder.Entity<UserModel>(b =>
            {
                b.Property<string>("email")
                    .HasColumnType("nvarchar(450)");

                b.Property<DateTime>("endDate")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("initialDate")
                    .HasColumnType("datetime2");

                b.Property<string>("name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("email");

                b.ToTable("User");
            });

            modelBuilder.Entity<OrderModel>(b =>
            {
                b.HasOne("ProductModel", "product")
                    .WithMany()
                    .HasForeignKey("productCode")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("product");
            });
#pragma warning restore 612, 618
        }
    }
}
